# Generated by Django 4.1.3 on 2022-11-24 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_subjects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('debts', '0002_debt_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='debt',
            unique_together={('user', 'receipt')},
        ),
    ]
