# Generated by Django 4.1.3 on 2022-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debt_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
