# Generated by Django 4.1.3 on 2022-11-26 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_receipt_name'),
        ('debts', '0004_alter_debt_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='receipts.receipt')),
            ],
        ),
    ]
