# Generated by Django 4.1.3 on 2022-11-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0006_personreceiptdebts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempDebts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='debts.debt')),
            ],
        ),
    ]
