# Generated by Django 4.1.3 on 2023-05-28 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'Участник группы', 'verbose_name_plural': 'Участники группы'},
        ),
    ]
