#for local use
version: '2'
volumes:
  logs:
  postgres-data:

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    # command: sh build.sh
    volumes:
      - .:/code
      - ./media:/code/media
    ports:
      - "8000:8000"
    networks:
      - wallet_network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    networks:
      - wallet_network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

networks:
  wallet_network: