# Generated by Django 4.1.3 on 2023-05-27 23:22

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='groups.group')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to='groups.groupmember')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='groups.group')),
                ('participants', models.ManyToManyField(related_name='receipts', to='groups.groupmember')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('count', models.PositiveIntegerField(default=1)),
                ('total_amount', models.DecimalField(decimal_places=3, default=0, max_digits=15)),
                ('categories', models.ManyToManyField(to='receipts.category')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('group_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='groups.groupmember')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payers', to='receipts.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.DecimalField(decimal_places=3, max_digits=15)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=15)),
                ('group_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_participantions', to='groups.groupmember')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='receipts.position')),
            ],
        ),
    ]
