# Generated by Django 4.1.3 on 2023-05-27 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmember_options_and_more'),
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='participant',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='payer',
            options={'verbose_name': 'Плательщик', 'verbose_name_plural': 'Плательщики'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Позиция', 'verbose_name_plural': 'Позиции'},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'verbose_name': 'Чек', 'verbose_name_plural': 'Чеки'},
        ),
        migrations.AddField(
            model_name='position',
            name='participants',
            field=models.ManyToManyField(through='receipts.Participant', to='groups.groupmember'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.position'),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
