# Generated by Django 4.1.3 on 2023-05-28 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmember_options_and_more'),
        ('receipts', '0004_alter_category_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='participants',
        ),
        migrations.AlterField(
            model_name='participant',
            name='amount',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='group_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='position_participantions', to='groups.groupmember', verbose_name='Член группы'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='part',
            field=models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Часть'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.position', verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='position',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='position',
            name='categories',
            field=models.ManyToManyField(to='receipts.category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='position',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='position',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='receipts.receipt', verbose_name='Чек'),
        ),
        migrations.AlterField(
            model_name='position',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15, verbose_name='Итоговая цена'),
        ),
    ]
