# Generated by Django 4.1.3 on 2023-05-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmember_options_and_more'),
        ('receipts', '0005_remove_position_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='participants',
            field=models.ManyToManyField(to='groups.groupmember', verbose_name='Участники'),
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
