# Generated by Django 4.1.3 on 2022-11-24 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('receipts', '0002_payer_user_position_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='subjects',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
