# Generated by Django 4.1.3 on 2022-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_receipt_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
