# Generated by Django 4.1.3 on 2023-05-27 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPersonalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptPersonalDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='TempDebts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp', to='debts.receiptdebt')),
            ],
        ),
    ]
