# Generated by Django 4.1.3 on 2023-05-27 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_options_alter_groupmember_options_and_more'),
        ('debts', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouppersonaldebt',
            options={'verbose_name': 'Личный долг в группе', 'verbose_name_plural': 'Личные долги в группе'},
        ),
        migrations.AlterModelOptions(
            name='receiptdebt',
            options={'verbose_name': 'Долг по чеку', 'verbose_name_plural': 'Долги по чеку'},
        ),
        migrations.AlterModelOptions(
            name='receiptpersonaldebt',
            options={'verbose_name': 'Личный долг по чеку', 'verbose_name_plural': 'Личные долги по чеку'},
        ),
        migrations.AlterUniqueTogether(
            name='receiptpersonaldebt',
            unique_together={('debtor', 'creditor')},
        ),
    ]
